cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/php'

brew 'coreutils'

# Install xquartz first because some things depend on it
cask 'xquartz'

brew 'ack'
brew 'cabal-install'
brew 'curl'
brew 'ddate'
brew 'go'
brew 'git', args: ['without-completions']
brew 'gnupg'
brew 'gpg-agent'
brew 'pinentry-mac'
brew 'grc'
brew 'homebrew/php/composer'
brew 'homebrew/php/php71'
brew 'homebrew/php/phpunit'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'librsvg'
brew 'libyaml'
brew 'macvim'
brew 'mysql'
brew 'node'
brew 'openssl'
brew 'optipng'
brew 'python'
brew 'tag'
brew 'tree'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

cask '1password'
cask 'a-better-finder-rename'
cask 'alfred'
cask 'appcleaner'
cask 'ascension'
cask 'atom'
cask 'audio-hijack'
cask 'bartender'
cask 'calibre'
cask 'cloud'
cask 'colloquy'
cask 'crashplan'
cask 'dropbox'
cask 'firefox'
cask 'dupeguru'
cask 'fantastical'
cask 'flux'
cask 'gimp'
cask 'google-chrome'
cask 'istat-menus'
cask 'iterm2'
cask 'kaleidoscope'
cask 'kid3'
cask 'little-snitch'
cask 'livereload'
cask 'marked'
cask 'moom'
cask 'nvalt'
cask 'private-internet-access'
cask 'screenhero'
cask 'sequel-pro'
cask 'skype'
cask 'spotify'
cask 'swinsian'
cask 'the-unarchiver'
cask 'transmit'
cask 'vlc'
