update

upgrade

# Install GNU core utilities
#
# http://www.gnu.org/software/coreutils/
#
# This installs all of the basic command-line utilities for the GNU/Linux
# operating system. Your Mac will be supercharged with the power of GNU.
install coreutils

# Install Homebrew Cask
#
# http://caskroom.io/
#
# Cask allows us to install thousands of Mac apps from the command line.
install phinze/cask/brew-cask

# Install formulae
install ack
install bash
install bash-completion
install cabal-install
install ffmpeg
install git --without-completions # Completions break oh-my-zsh (because it installs its own completions)
install git-flow
install graphicsmagick
install grc
install hub
install jpeg
install node
install optipng
install osxfuse
install phantomjs
install python
install spark
install tree
install wget
install zsh

# Install PHP 5.5 and Composer from @josegonzalez's repo
#
# https://github.com/josegonzalez/homebrew-php
# https://getcomposer.org/doc/00-intro.md#globally-on-osx-via-homebrew-
tap homebrew/dupes
tap homebrew/versions
tap josegonzalez/homebrew-php

install php55
install composer

cleanup
