#!/bin/sh
# Setup a machine for Sublime Text 3

# Set up Package Control the hard way
cd $HOME/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages
curl -Lo "Package Control.sublime-package" https://sublime.wbond.net/Package%20Control.sublime-package
cd -

# symlink settings in
sublime_dir=$HOME/Library/Application\ Support/Sublime\ Text\ 3/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$DOTFILES/sublime3/User" "$sublime_dir"

# Grab the Spacegray theme
cd "$sublime_dir"
git clone https://github.com/kkga/spacegray.git "Theme - Spacegray"
