#!/bin/sh
# Setup a machine for Sublime Text 3
set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 3/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$DOTFILES/sublime3/User" "$sublime_dir"

# Grab the Spacegray theme
cd "$sublime_dir"
git clone https://github.com/kkga/spacegray.git "Theme - Spacegray"
