#!/bin/bash
#
# bootstrap installs things.

set -e

DOTFILES_ROOT="$(pwd)"

echo ''

# Include utilities
source "$HOME/.dotfiles/lib/utils.zsh"

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    e_header 'Setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    e_header ' - What is your github author name?'
    read -e git_authorname
    e_header ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    e_success 'gitconfig'
  fi
}

install_dotfiles () {
  e_header 'Installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    if [ -f $dest ] || [ -d $dest ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        e_header "File already exists: $(basename "$source"), what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf "$dest"
        e_success "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv "$dest" "$dest\.backup"
        e_success "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files "$source" "$dest"
      else
        e_success "skipped $source"
      fi

    else
      link_files "$source" "$dest"
    fi

  done
}

set_fish_shell() {
  if grep --quiet fish <<< "$SHELL"; then
    success "Fish shell is already set up."
  else
    substep_info "Adding fish executable to /etc/shells"
    if grep --fixed-strings --line-regexp --quiet "/usr/local/bin/fish" /etc/shells; then
      substep_success "Fish executable already exists in /etc/shells."
    else
      if sudo bash -c "echo /usr/local/bin/fish >> /etc/shells"; then
        substep_success "Fish executable added to /etc/shells."
      else
        substep_error "Failed adding Fish executable to /etc/shells."
        return 1
      fi
    fi
    substep_info "Changing shell to fish"
    if sudo chsh -s /usr/local/bin/fish; then
      substep_success "Changed shell to fish"
    else
      substep_error "Failed changing shell to fish"
      return 2
    fi
    substep_info "Running fish initial setup"
    fish -c "setup"
  fi
}

vim_go () {
  # Install much Vim
  #
  # From @necolas' dotfiles
  #
  # Note that the `.symlink` files will still (needlessly) exist in the
  # symlinked `~/.vim` directory, but they won't do any harm there.
  e_header "Installing Vim things"
  ln -Ffs "$DOTFILES_ROOT/vim" "$HOME/.vim"
  e_success "Vim things installed."
}

setup_gitconfig
install_dotfiles
vim_go

# Set macOS defaults
if [ "$(uname -s)" == "Darwin" ]; then
  $DOTFILES_ROOT/macos/set-defaults.sh
fi

if test ! $(which brew)
then
  e_header "Installing Homebrew"

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

e_header "Installing dependencies"
  source bin/dot 2> /tmp/dotfiles-dot
  if [[ $? ]]
  then
    e_success "Dependencies installed"
  else
    e_fail "Error installing dependencies"
  fi

set_fish_shell

echo ''
echo '  All installed!'
echo ''
