#!/usr/bin/env bash
#
# Run all dotfiles installers.


cd "$HOME/.dotfiles"

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
